services:
  agent4_bos:
    build: .
    container_name: agent4_bos
    ports:
      - "8004:8000"
    networks:
      - ai_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - COLLECTION=zapytania_agent_4

networks:
  ai_network:
    external: true

